// Auto-generated by formal/scripts/prepare_equiv_check.py
// Wraps the original bad_mac_array with 1 extra output
// register(s), matching candidate_008's reported LATENCY_DELTA_CYCLES,
// so equivalence checking compares both designs at the same total latency.
module bad_mac_array (
    input clk,
    input rst_n,
    input [15:0] a0, a1, a2, a3,
    input [15:0] b0, b1, b2, b3,
    output reg [31:0] out
);
    wire [31:0] out_orig;
    

    bad_mac_array_core original_inst (
        .clk(clk),
        .rst_n(rst_n),
        .a0(a0),
        .a1(a1),
        .a2(a2),
        .a3(a3),
        .b0(b0),
        .b1(b1),
        .b2(b2),
        .b3(b3),
        .out(out_orig)
    );

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            
            out <= 'd0;
        end else begin
            
            out <= out_orig;
        end
    end
endmodule
