// Auto-generated by formal/scripts/prepare_equiv_check.py
// Wraps the original bad_adder_chain with 2 extra output
// register(s), matching candidate_005's reported LATENCY_DELTA_CYCLES,
// so equivalence checking compares both designs at the same total latency.
module bad_adder_chain (
    input clk,
    input rst_n,
    input [31:0] a, b, c, d, e, f, g, h,
    output reg [31:0] out
);
    wire [31:0] out_orig;
    reg [31:0] out_d1;

    bad_adder_chain_core original_inst (
        .clk(clk),
        .rst_n(rst_n),
        .a(a),
        .b(b),
        .c(c),
        .d(d),
        .e(e),
        .f(f),
        .g(g),
        .h(h),
        .out(out_orig)
    );

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            out_d1 <= 'd0;
            out <= 'd0;
        end else begin
            out_d1 <= out_orig;
            out <= out_d1;
        end
    end
endmodule
